# Car Price Prediction ML

In [1]:
import pandas as pd
data = pd.read_csv('C:\\Users\\HP\\Downloads\\archive (19)\\car data.csv')
data.head(10)


Car_Name  Year  Selling_Price  Present_Price  Driven_kms Fuel_Type  \
0           ritz  2014           3.35           5.59       27000    Petrol   
1            sx4  2013           4.75           9.54       43000    Diesel   
2           ciaz  2017           7.25           9.85        6900    Petrol   
3        wagon r  2011           2.85           4.15        5200    Petrol   
4          swift  2014           4.60           6.87       42450    Diesel   
5  vitara brezza  2018           9.25           9.83        2071    Diesel   
6           ciaz  2015           6.75           8.12       18796    Petrol   
7        s cross  2015           6.50           8.61       33429    Diesel   
8           ciaz  2016           8.75           8.89       20273    Diesel   
9           ciaz  2015           7.45           8.92       42367    Diesel   

  Selling_type Transmission  Owner  
0       Dealer       Manual      0  
1       Dealer       Manual      0  
2       Dealer       Manual      0  
3       Dealer       Manual      0  
4       Dealer       Manual      0  
5       Dealer       Manual      0  
6       Dealer       Manual      0  
7       Dealer       Manual      0  
8       Dealer       Manual      0  
9       Dealer       Manual      0

In [2]:
data.describe()

Year  Selling_Price  Present_Price     Driven_kms       Owner
count   301.000000     301.000000     301.000000     301.000000  301.000000
mean   2013.627907       4.661296       7.628472   36947.205980    0.043189
std       2.891554       5.082812       8.642584   38886.883882    0.247915
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.900000       1.200000   15000.000000    0.000000
50%    2014.000000       3.600000       6.400000   32000.000000    0.000000
75%    2016.000000       6.000000       9.900000   48767.000000    0.000000
max    2018.000000      35.000000      92.600000  500000.000000    3.000000

In [3]:
data['Fuel_Type'].unique()

array(['Petrol', 'Diesel', 'CNG'], dtype=object)

In [4]:
data.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Driven_kms       0
Fuel_Type        0
Selling_type     0
Transmission     0
Owner            0
dtype: int64

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Car_Name       301 non-null    object 
 1   Year           301 non-null    int64  
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Driven_kms     301 non-null    int64  
 5   Fuel_Type      301 non-null    object 
 6   Selling_type   301 non-null    object 
 7   Transmission   301 non-null    object 
 8   Owner          301 non-null    int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB


In [6]:
from sklearn import preprocessing
# Categorizing the data with three or less 
le=preprocessing.LabelEncoder()

In [7]:
encoded_fuel= le.fit_transform(data['Fuel_Type'])
encoded_transmission= le.fit_transform(data['Transmission'])
encoded_selling= le.fit_transform(data['Selling_type'])

In [8]:
data['Fuel_encoded']=encoded_fuel
data['Transmission_encoded']=encoded_transmission
data['Sellingtype_encoded']=encoded_selling

In [9]:
data.drop(['Transmission','Selling_type','Fuel_Type','Car_Name'], axis=1,inplace=True)

In [10]:
data['Selling_Price'] = data['Selling_Price'].round().astype(int)
data['Present_Price'] = data['Present_Price'].round().astype(int)
data.head()

Year  Selling_Price  Present_Price  Driven_kms  Owner  Fuel_encoded  \
0  2014              3              6       27000      0             2   
1  2013              5             10       43000      0             1   
2  2017              7             10        6900      0             2   
3  2011              3              4        5200      0             2   
4  2014              5              7       42450      0             1   

   Transmission_encoded  Sellingtype_encoded  
0                     1                    0  
1                     1                    0  
2                     1                    0  
3                     1                    0  
4                     1                    0

In [11]:
# Import the package for splitting dataset

from sklearn.model_selection import train_test_split

In [12]:
data.columns

Index(['Year', 'Selling_Price', 'Present_Price', 'Driven_kms', 'Owner',
       'Fuel_encoded', 'Transmission_encoded', 'Sellingtype_encoded'],
      dtype='object')

In [13]:
X = data[['Year','Selling_Price','Driven_kms','Owner','Fuel_encoded','Transmission_encoded','Sellingtype_encoded']]
y = data[['Present_Price']]

In [14]:
# train_test_split(X,y,train_size=0.8)  # Percentage of the data I'd want (That is 400 samples)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
sc= StandardScaler()
X_train =sc.fit_transform(X_train)

In [17]:
# Confirming that the scaling has occurred
X_train

array([[-1.96986094, -0.88504165, -0.27555466, ...,  0.48236665,
         0.37796447,  1.33816952],
       [ 1.15644297, -0.69211704, -0.81428242, ...,  0.48236665,
         0.37796447,  1.33816952],
       [-1.96986094, -0.88504165,  0.29908829, ...,  0.48236665,
         0.37796447,  1.33816952],
       ...,
       [ 0.11434167, -0.69211704, -0.50301749, ...,  0.48236665,
         0.37796447,  1.33816952],
       [-0.92775963, -0.11334321,  0.76217867, ...,  0.48236665,
         0.37796447, -0.74728947],
       [ 1.15644297, -0.49919243, -0.8023107 , ...,  0.48236665,
         0.37796447,  1.33816952]])

In [18]:
X_test=sc.transform(X_test)

In [19]:
X_test

array([[ 0.80907587, -0.88504165, -0.32344157, -0.18569534,  0.48236665,
        -2.64575131,  1.33816952],
       [ 0.80907587,  1.04420446, -0.63518537, -0.18569534,  0.48236665,
         0.37796447, -0.74728947],
       [-0.58039253,  0.0795814 ,  0.53852285, -0.18569534, -1.88024551,
         0.37796447, -0.74728947],
       [-0.92775963, -0.88504165, -0.06006356,  3.52821143,  0.48236665,
         0.37796447,  1.33816952],
       [-0.23302543,  0.46543062,  0.05967767, -0.18569534,  0.48236665,
         0.37796447, -0.74728947],
       [ 0.46170877,  0.46543062,  0.11632788, -0.18569534, -1.88024551,
         0.37796447, -0.74728947],
       [ 0.46170877, -0.69211704, -0.27555466, -0.18569534,  0.48236665,
         0.37796447,  1.33816952],
       [ 0.11434167, -0.88504165, -0.70653687, -0.18569534,  0.48236665,
         0.37796447,  1.33816952],
       [ 0.80907587, -0.88504165, -0.56287614, -0.18569534,  0.48236665,
         0.37796447,  1.33816952],
       [ 0.11434167,  0.2725

In [20]:
from sklearn.linear_model import LinearRegression

In [21]:
# giving a variable name to our algorithm
lr= LinearRegression()

In [22]:
lr.fit(X_train, y_train)

LinearRegression()

In [23]:
data.describe()

Year  Selling_Price  Present_Price     Driven_kms       Owner  \
count   301.000000     301.000000     301.000000     301.000000  301.000000   
mean   2013.627907       4.611296       7.710963   36947.205980    0.043189   
std       2.891554       5.129497       8.649827   38886.883882    0.247915   
min    2003.000000       0.000000       0.000000     500.000000    0.000000   
25%    2012.000000       1.000000       1.000000   15000.000000    0.000000   
50%    2014.000000       4.000000       6.000000   32000.000000    0.000000   
75%    2016.000000       6.000000      10.000000   48767.000000    0.000000   
max    2018.000000      35.000000      93.000000  500000.000000    3.000000   

       Fuel_encoded  Transmission_encoded  Sellingtype_encoded  
count    301.000000            301.000000           301.000000  
mean       1.787375              0.867110             0.352159  
std        0.425801              0.340021             0.478439  
min        0.000000              0.000000             0.000000  
25%        2.000000              1.000000             0.000000  
50%        2.000000              1.000000             0.000000  
75%        2.000000              1.000000             1.000000  
max        2.000000              1.000000             1.000000

In [24]:
data.describe().T

count          mean           std     min      25%  \
Year                  301.0   2013.627907      2.891554  2003.0   2012.0   
Selling_Price         301.0      4.611296      5.129497     0.0      1.0   
Present_Price         301.0      7.710963      8.649827     0.0      1.0   
Driven_kms            301.0  36947.205980  38886.883882   500.0  15000.0   
Owner                 301.0      0.043189      0.247915     0.0      0.0   
Fuel_encoded          301.0      1.787375      0.425801     0.0      2.0   
Transmission_encoded  301.0      0.867110      0.340021     0.0      1.0   
Sellingtype_encoded   301.0      0.352159      0.478439     0.0      0.0   

                          50%      75%       max  
Year                   2014.0   2016.0    2018.0  
Selling_Price             4.0      6.0      35.0  
Present_Price             6.0     10.0      93.0  
Driven_kms            32000.0  48767.0  500000.0  
Owner                     0.0      0.0       3.0  
Fuel_encoded              2.0      2.0       2.0  
Transmission_encoded      1.0      1.0       1.0  
Sellingtype_encoded       0.0      1.0       1.0

In [25]:
lr.intercept_

array([7.59583333])

In [26]:
coeff= lr.coef_.T

In [27]:
coeff

array([[-1.95124234],
       [ 8.73502645],
       [ 0.46848771],
       [ 0.58344938],
       [ 0.33520624],
       [ 0.16931754],
       [ 0.1475348 ]])

In [28]:
X.columns

Index(['Year', 'Selling_Price', 'Driven_kms', 'Owner', 'Fuel_encoded',
       'Transmission_encoded', 'Sellingtype_encoded'],
      dtype='object')

In [29]:
 pd.DataFrame(coeff,X.columns,columns=['Coefficient'])

Coefficient
Year                    -1.951242
Selling_Price            8.735026
Driven_kms               0.468488
Owner                    0.583449
Fuel_encoded             0.335206
Transmission_encoded     0.169318
Sellingtype_encoded      0.147535

In [30]:
predictions= lr.predict(X_test)

In [31]:
predictions

array([[-2.06245747e+00],
       [ 1.48478006e+01],
       [ 8.89088776e+00],
       [ 4.12876356e+00],
       [ 1.21511228e+01],
       [ 1.00301056e+01],
       [ 8.34944040e-01],
       [-3.74370018e-01],
       [-1.66266152e+00],
       [ 9.05223633e+00],
       [ 1.09151077e+01],
       [ 2.26905933e+00],
       [ 1.23661173e+01],
       [-2.99488565e+00],
       [ 9.73003373e+00],
       [ 5.68548595e+00],
       [ 2.70568661e+00],
       [ 2.59408390e+01],
       [-2.40103187e+00],
       [ 8.88607346e-01],
       [ 3.48296237e-01],
       [ 1.07802654e+01],
       [ 8.58041769e+00],
       [ 6.54155572e+00],
       [ 1.50152422e+00],
       [ 7.71721814e+00],
       [ 8.96804711e+00],
       [ 6.79955167e+00],
       [-6.88908974e-01],
       [ 6.74089254e-02],
       [ 2.07836668e+00],
       [ 1.26245494e+01],
       [ 2.54994665e+00],
       [ 7.31600049e+00],
       [ 1.10446103e+01],
       [ 6.36162335e+00],
       [ 1.08248609e+01],
       [ 1.00534751e+01],
       [ 5.5

In [32]:
import numpy as np

In [33]:
from sklearn.metrics import r2_score

In [34]:
r2_score(y_test, predictions)

0.786159021729525

In [35]:
import statsmodels.api as sm

In [36]:
# Add a aconstant term to the input data
X_train =sm.add_constant(X_train)

In [37]:
model=sm.OLS(y_train,X_train)
results=model.fit()

In [38]:
results.params

const    7.595833
x1      -1.951242
x2       8.735026
x3       0.468488
x4       0.583449
x5       0.335206
x6       0.169318
x7       0.147535
dtype: float64

In [39]:
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:          Present_Price   R-squared:                       0.848
Model:                            OLS   Adj. R-squared:                  0.843
Method:                 Least Squares   F-statistic:                     184.4
Date:                Thu, 03 Apr 2025   Prob (F-statistic):           4.76e-91
Time:                        11:55:34   Log-Likelihood:                -641.47
No. Observations:                 240   AIC:                             1299.
Df Residuals:                     232   BIC:                             1327.
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          7.5958      0.230     33.020      0.0